import type { ThemeDefinition } from "./theme.js";

function textBox(
  x: number,
  y: number,
  width: number,
  height: number,
  overrides: Partial<ThemeDefinition["components"]["homeName"]>
): ThemeDefinition["components"]["homeName"] {
  const component = {
    kind: "text" as const,
    x,
    y,
    width,
    height,
    zIndex: 1,
    visible: true,
    opacity: 1,
    backgroundColor: "#00000000",
    borderColor: "#00000000",
    borderWidth: 0,
    borderRadius: 0,
    padding: 16,
    shadow: "none",
    fontFamily: "Oswald",
    fontSize: 48,
    fontWeight: 700,
    color: "#ffffff",
    textAlign: "center",
    letterSpacing: 1.5,
    lineHeight: 1,
    ...overrides
  };
  return {
    ...component,
    backgroundImageAssetId: component.backgroundImageAssetId ?? null,
    backgroundImageFit: component.backgroundImageFit ?? "cover",
    backgroundImagePosition: component.backgroundImagePosition ?? "center",
    backgroundOverlayColor: component.backgroundOverlayColor ?? "#000000",
    backgroundOverlayOpacity: component.backgroundOverlayOpacity ?? 0
  } as ThemeDefinition["components"]["homeName"];
}

function logoBox(overrides: Partial<ThemeDefinition["components"]["eventLogo"]>): ThemeDefinition["components"]["eventLogo"] {
  const component = {
    kind: "image" as const,
    x: 900,
    y: 24,
    width: 120,
    height: 120,
    zIndex: 4,
    visible: false,
    opacity: 1,
    backgroundColor: "#00000000",
    borderColor: "#00000000",
    borderWidth: 0,
    borderRadius: 0,
    padding: 0,
    shadow: "none",
    assetId: null,
    teamLogoFallbackMode: "slotFallback",
    ...overrides
  };
  return {
    ...component,
    backgroundImageAssetId: component.backgroundImageAssetId ?? null,
    backgroundImageFit: component.backgroundImageFit ?? "cover",
    backgroundImagePosition: component.backgroundImagePosition ?? "center",
    backgroundOverlayColor: component.backgroundOverlayColor ?? "#000000",
    backgroundOverlayOpacity: component.backgroundOverlayOpacity ?? 0
  } as ThemeDefinition["components"]["eventLogo"];
}

function teamEventOverlay(
  overrides: {
    general?: Partial<ThemeDefinition["teamEventOverlay"]["general"]>;
    concede?: Partial<ThemeDefinition["teamEventOverlay"]["concede"]>;
    base?: Partial<ThemeDefinition["teamEventOverlay"]["base"]>;
  } = {}
): ThemeDefinition["teamEventOverlay"] {
  return {
    general: {
      enabled: true,
      position: "above",
      placementMode: "center-stamp",
      offsetX: 0,
      offsetY: -8,
      height: 44,
      padding: 12,
      backgroundImageFit: "cover",
      backgroundImagePosition: "center",
      borderColor: "#ffffff",
      borderWidth: 2,
      borderRadius: 12,
      fontFamily: "Oswald",
      fontSize: 28,
      fontWeight: 700,
      letterSpacing: 1,
      textAlign: "center",
      shadow: "none",
      animationPreset: "slide-vertical",
      durationMs: 2000,
      followLogoSize: false,
      ...(overrides.general ?? {})
    },
    concede: {
      text: "Conceded",
      color: "#ffffff",
      backgroundColor: "#111111ee",
      backgroundImageAssetId: null,
      backgroundOverlayColor: "#000000",
      backgroundOverlayOpacity: 0,
      ...(overrides.concede ?? {})
    },
    base: {
      text: "Base",
      color: "#ffd54f",
      backgroundColor: "#1b3b6fff",
      backgroundImageAssetId: null,
      backgroundOverlayColor: "#000000",
      backgroundOverlayOpacity: 0,
      ...(overrides.base ?? {})
    }
  };
}

export const builtinThemes: ThemeDefinition[] = [
  {
    "id": "theme-7ad8adb8-e017-4853-93b1-fb608a750253",
    "name": "Broadcast Logos",
    "description": "Reference-style broadcast bar with full-width team logo panels and compact stacked center timing.",
    "builtin": true,
    "canvas": {
      "width": 1920,
      "height": 1080,
      "backgroundColor": "#00b140",
      "transparentPreview": false,
      "safeArea": true
    },
    "components": {
      "homeName": {
        "x": 362,
        "y": 343,
        "width": 425,
        "height": 44,
        "zIndex": 1,
        "visible": true,
        "opacity": 1,
        "backgroundColor": "#2a2724f2",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#6f5d49",
        "borderWidth": 1,
        "borderRadius": 0,
        "padding": 6,
        "shadow": "none",
        "kind": "text",
        "fontFamily": "Bebas Neue",
        "fontSize": 26,
        "fontWeight": 700,
        "color": "#ffffff",
        "textAlign": "center",
        "letterSpacing": 1.1,
        "lineHeight": 1
      },
      "homeTeamLogo": {
        "x": 362,
        "y": 273,
        "width": 424,
        "height": 71,
        "zIndex": 2,
        "visible": true,
        "opacity": 1,
        "backgroundColor": "#2a2724f2",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#6f5d49",
        "borderWidth": 1,
        "borderRadius": 0,
        "padding": 0,
        "shadow": "none",
        "kind": "image",
        "assetId": null,
        "teamLogoFallbackMode": "eventLogo"
      },
      "homeScore": {
        "x": 787,
        "y": 273,
        "width": 94,
        "height": 71,
        "zIndex": 1,
        "visible": true,
        "opacity": 1,
        "backgroundColor": "#f6f1e8",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#2a2522",
        "borderWidth": 2,
        "borderRadius": 0,
        "padding": 0,
        "shadow": "none",
        "kind": "text",
        "fontFamily": "Arial Narrow",
        "fontSize": 70,
        "fontWeight": 700,
        "color": "#111111",
        "textAlign": "center",
        "letterSpacing": 0,
        "lineHeight": 0.92
      },
      "awayName": {
        "x": 1133,
        "y": 343,
        "width": 425,
        "height": 44,
        "zIndex": 1,
        "visible": true,
        "opacity": 1,
        "backgroundColor": "#2a2724f2",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#6f5d49",
        "borderWidth": 1,
        "borderRadius": 0,
        "padding": 6,
        "shadow": "none",
        "kind": "text",
        "fontFamily": "Bebas Neue",
        "fontSize": 26,
        "fontWeight": 700,
        "color": "#ffffff",
        "textAlign": "center",
        "letterSpacing": 1.1,
        "lineHeight": 1
      },
      "awayTeamLogo": {
        "x": 1134,
        "y": 273,
        "width": 424,
        "height": 71,
        "zIndex": 2,
        "visible": true,
        "opacity": 1,
        "backgroundColor": "#2a2724f2",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#6f5d49",
        "borderWidth": 1,
        "borderRadius": 0,
        "padding": 0,
        "shadow": "none",
        "kind": "image",
        "assetId": null,
        "teamLogoFallbackMode": "eventLogo"
      },
      "awayScore": {
        "x": 1039,
        "y": 273,
        "width": 94,
        "height": 71,
        "zIndex": 1,
        "visible": true,
        "opacity": 1,
        "backgroundColor": "#f6f1e8",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#2a2522",
        "borderWidth": 2,
        "borderRadius": 0,
        "padding": 0,
        "shadow": "none",
        "kind": "text",
        "fontFamily": "Arial Narrow",
        "fontSize": 70,
        "fontWeight": 700,
        "color": "#111111",
        "textAlign": "center",
        "letterSpacing": 0,
        "lineHeight": 0.92
      },
      "gameTime": {
        "x": 882,
        "y": 273,
        "width": 156,
        "height": 70,
        "zIndex": 1,
        "visible": true,
        "opacity": 1,
        "backgroundColor": "#111111f4",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#2a2522",
        "borderWidth": 2,
        "borderRadius": 0,
        "padding": 4,
        "shadow": "none",
        "kind": "text",
        "fontFamily": "Bebas Neue",
        "fontSize": 38,
        "fontWeight": 700,
        "color": "#ffffff",
        "textAlign": "center",
        "letterSpacing": 0.8,
        "lineHeight": 1
      },
      "breakTime": {
        "x": 787,
        "y": 344,
        "width": 346,
        "height": 35,
        "zIndex": 1,
        "visible": true,
        "opacity": 1,
        "backgroundColor": "#111111f4",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#2a2522",
        "borderWidth": 2,
        "borderRadius": 0,
        "padding": 2,
        "shadow": "none",
        "kind": "text",
        "fontFamily": "Barlow Condensed",
        "fontSize": 24,
        "fontWeight": 700,
        "color": "#21e25b",
        "textAlign": "center",
        "letterSpacing": 0.4,
        "lineHeight": 1
      },
      "eventLogo": {
        "x": 882,
        "y": 207,
        "width": 156,
        "height": 44,
        "zIndex": 4,
        "visible": false,
        "opacity": 1,
        "backgroundColor": "transparent",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0.5,
        "borderColor": "#00000000",
        "borderWidth": 0,
        "borderRadius": 0,
        "padding": 0,
        "shadow": "none",
        "kind": "image",
        "assetId": "asset-56610d6a-81e8-4118-a4ff-740214176d01",
        "teamLogoFallbackMode": "slotFallback"
      }
    },
    "teamEventOverlay": teamEventOverlay({
      general: {
        placementMode: "center-stamp",
        position: "overlapping-top",
        offsetY: -8,
        height: 58,
        padding: 10,
        borderColor: "transparent",
        borderWidth: 2,
        borderRadius: 10,
        fontFamily: "Barlow Condensed",
        fontSize: 42,
        fontWeight: 700,
        letterSpacing: 1.5,
        textAlign: "center",
        animationPreset: "slide-horizontal",
        durationMs: 2000,
        followLogoSize: false
      },
      concede: {
        text: "TOWEL",
        color: "#ffffff",
        backgroundColor: "#000000",
        backgroundImageAssetId: null,
        backgroundOverlayColor: "#ff0000",
        backgroundOverlayOpacity: 0.81
      },
      base: {
        text: "BASE",
        color: "#ffd54f",
        backgroundColor: "#1b3b6fff",
        backgroundImageAssetId: null,
        backgroundOverlayColor: "#000000",
        backgroundOverlayOpacity: 0
      }
    }),
    "centerSecondary": {
      "gameMode": "staticText",
      "gameText": "SOUTHERNLEGION RACE SERIES",
      "breakMode": "timer",
      "breakText": "",
      "timerStyle": {
        "fontFamily": "Barlow Condensed",
        "fontSize": 28,
        "fontWeight": 700,
        "color": "#66ff00"
      },
      "staticStyle": {
        "fontFamily": "Barlow Condensed",
        "fontSize": 25,
        "fontWeight": 700,
        "color": "#f6f1e8"
      },
      "transition": {
        "animation": "fade",
        "durationMs": 250
      }
    }
  },
  {
    "id": "builtin-minimal-strip",
    "name": "Broadcast Clean",
    "description": "Reference-style broadcast bar without logo artwork, keeping the same geometry and center stack.",
    "builtin": true,
    "canvas": {
      "width": 1920,
      "height": 1080,
      "backgroundColor": "#00b140",
      "transparentPreview": false,
      "safeArea": true
    },
    "components": {
      "homeName": {
        "x": 132,
        "y": 30,
        "width": 520,
        "height": 106,
        "zIndex": 1,
        "visible": true,
        "opacity": 1,
        "backgroundColor": "#2a2724f2",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#6f5d49",
        "borderWidth": 1,
        "borderRadius": 0,
        "padding": 10,
        "shadow": "none",
        "kind": "text",
        "fontFamily": "Bebas Neue",
        "fontSize": 54,
        "fontWeight": 700,
        "color": "#ffffff",
        "textAlign": "center",
        "letterSpacing": 1.2,
        "lineHeight": 1
      },
      "homeTeamLogo": {
        "x": 132,
        "y": 30,
        "width": 520,
        "height": 68,
        "zIndex": 2,
        "visible": false,
        "opacity": 1,
        "backgroundColor": "#00000000",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#00000000",
        "borderWidth": 0,
        "borderRadius": 0,
        "padding": 0,
        "shadow": "none",
        "kind": "image",
        "assetId": null,
        "teamLogoFallbackMode": "none"
      },
      "homeScore": {
        "x": 670,
        "y": 30,
        "width": 156,
        "height": 106,
        "zIndex": 1,
        "visible": true,
        "opacity": 1,
        "backgroundColor": "#f6f1e8",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#2a2522",
        "borderWidth": 2,
        "borderRadius": 0,
        "padding": 0,
        "shadow": "none",
        "kind": "text",
        "fontFamily": "Bebas Neue",
        "fontSize": 96,
        "fontWeight": 700,
        "color": "#111111",
        "textAlign": "center",
        "letterSpacing": 1.5,
        "lineHeight": 1
      },
      "awayName": {
        "x": 1264,
        "y": 30,
        "width": 520,
        "height": 106,
        "zIndex": 1,
        "visible": true,
        "opacity": 1,
        "backgroundColor": "#2a2724f2",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#6f5d49",
        "borderWidth": 1,
        "borderRadius": 0,
        "padding": 10,
        "shadow": "none",
        "kind": "text",
        "fontFamily": "Bebas Neue",
        "fontSize": 54,
        "fontWeight": 700,
        "color": "#ffffff",
        "textAlign": "center",
        "letterSpacing": 1.2,
        "lineHeight": 1
      },
      "awayTeamLogo": {
        "x": 1264,
        "y": 30,
        "width": 520,
        "height": 68,
        "zIndex": 2,
        "visible": false,
        "opacity": 1,
        "backgroundColor": "#00000000",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#00000000",
        "borderWidth": 0,
        "borderRadius": 0,
        "padding": 0,
        "shadow": "none",
        "kind": "image",
        "assetId": null,
        "teamLogoFallbackMode": "none"
      },
      "awayScore": {
        "x": 1090,
        "y": 30,
        "width": 156,
        "height": 106,
        "zIndex": 1,
        "visible": true,
        "opacity": 1,
        "backgroundColor": "#f6f1e8",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#2a2522",
        "borderWidth": 2,
        "borderRadius": 0,
        "padding": 0,
        "shadow": "none",
        "kind": "text",
        "fontFamily": "Bebas Neue",
        "fontSize": 96,
        "fontWeight": 700,
        "color": "#111111",
        "textAlign": "center",
        "letterSpacing": 1.5,
        "lineHeight": 1
      },
      "gameTime": {
        "x": 849,
        "y": 47,
        "width": 218,
        "height": 42,
        "zIndex": 1,
        "visible": true,
        "opacity": 1,
        "backgroundColor": "#111111f4",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#2a2522",
        "borderWidth": 2,
        "borderRadius": 0,
        "padding": 4,
        "shadow": "none",
        "kind": "text",
        "fontFamily": "Bebas Neue",
        "fontSize": 44,
        "fontWeight": 700,
        "color": "#ffffff",
        "textAlign": "center",
        "letterSpacing": 0.8,
        "lineHeight": 1
      },
      "breakTime": {
        "x": 835,
        "y": 89,
        "width": 246,
        "height": 47,
        "zIndex": 1,
        "visible": true,
        "opacity": 1,
        "backgroundColor": "#111111f4",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#2a2522",
        "borderWidth": 2,
        "borderRadius": 0,
        "padding": 2,
        "shadow": "none",
        "kind": "text",
        "fontFamily": "Barlow Condensed",
        "fontSize": 24,
        "fontWeight": 700,
        "color": "#21e25b",
        "textAlign": "center",
        "letterSpacing": 0.4,
        "lineHeight": 1
      },
      "eventLogo": {
        "x": 905,
        "y": 28,
        "width": 106,
        "height": 20,
        "zIndex": 4,
        "visible": true,
        "opacity": 1,
        "backgroundColor": "#00000000",
        "backgroundImageAssetId": null,
        "backgroundImageFit": "cover",
        "backgroundImagePosition": "center",
        "backgroundOverlayColor": "#000000",
        "backgroundOverlayOpacity": 0,
        "borderColor": "#00000000",
        "borderWidth": 0,
        "borderRadius": 0,
        "padding": 0,
        "shadow": "none",
        "kind": "image",
        "assetId": null,
        "teamLogoFallbackMode": "slotFallback"
      }
    },
    "teamEventOverlay": teamEventOverlay({
      general: {
        placementMode: "top-ribbon",
        position: "above",
        offsetY: -8,
        height: 44,
        padding: 12,
        borderColor: "#111111",
        borderWidth: 2,
        borderRadius: 12,
        fontFamily: "Bebas Neue",
        fontSize: 32,
        fontWeight: 700,
        letterSpacing: 1.1,
        textAlign: "center",
        animationPreset: "slide-horizontal",
        durationMs: 2000,
        followLogoSize: false
      },
      concede: {
        text: "Conceded",
        color: "#111111",
        backgroundColor: "#f6f1e8",
        backgroundImageAssetId: null,
        backgroundOverlayColor: "#000000",
        backgroundOverlayOpacity: 0
      },
      base: {
        text: "BASE",
        color: "#ffd54f",
        backgroundColor: "#1b3b6fff",
        backgroundImageAssetId: null,
        backgroundOverlayColor: "#000000",
        backgroundOverlayOpacity: 0
      }
    }),
    "centerSecondary": {
      "gameMode": "staticText",
      "gameText": "MAJOR LEAGUE PAINTBALL",
      "breakMode": "timer",
      "breakText": "",
      "timerStyle": {
        "fontFamily": "Barlow Condensed",
        "fontSize": 24,
        "fontWeight": 700,
        "color": "#21e25b"
      },
      "staticStyle": {
        "fontFamily": "Barlow Condensed",
        "fontSize": 24,
        "fontWeight": 700,
        "color": "#21e25b"
      },
      "transition": {
        "animation": "fade",
        "durationMs": 220
      }
    }
  }
];
